apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
    stack: labs
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        envFrom:
        - configMapRef:
            name: toto
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
status: {}
